//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquiler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlquilerEntities : DbContext
    {
        public AlquilerEntities()
            : base("name=AlquilerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alquileres> Alquileres { get; set; }
        public DbSet<EstadosVehiculo> EstadosVehiculo { get; set; }
        public DbSet<tipoVehiculo> tipoVehiculo { get; set; }
        public DbSet<vehiculos> vehiculos { get; set; }
    }
}
