//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alquiler
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public vehiculos()
        {
            this.Alquileres = new HashSet<Alquileres>();
        }
    
        public int idVehiculo { get; set; }
        public string matricula { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> idTipoVehiculo { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> PesoToneladas { get; set; }
    
        public virtual ICollection<Alquileres> Alquileres { get; set; }
        public virtual EstadosVehiculo EstadosVehiculo { get; set; }
        public virtual tipoVehiculo tipoVehiculo { get; set; }
    }
}
